version: '{build}'
branches:
  only:
  - master
clone_depth: 10
cache:
  - win_flex_bison-latest.zip
matrix:
  fast_finish: true
environment:
  WINFLEXBISON_ARCHIVE: win_flex_bison-latest.zip
  PYTHON: "C:\\Python34-x64"
  PYTHON_VERSION: "3.4.3"
  PYTHON_ARCH: "64"
  matrix:
    - GENERATOR: "Visual Studio 13"
      ARCH: 32
    - GENERATOR: "Visual Studio 13"
      ARCH: 64
install:
  # Install flex/bison
  - if not exist %WINFLEXBISON_ARCHIVE% appveyor DownloadFile "https://sourceforge.net/projects/winflexbison/files/%WINFLEXBISON_ARCHIVE%"
  - 7z x -y %WINFLEXBISON_ARCHIVE%
  - set Path=%CD%\winflexbison;%Path%
  - win_flex --version
  - win_bison --version
build_script:
- ps: |
    mkdir build
    cmake . -Bbuild -G "Visual Studio 12 2013"
    msbuild /p:Configuration=Release build/mtex2MML.sln
test_script:
- ps: |
    cd build
    ctest -V
